In [96]:
import numpy as np



Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.



In [97]:
natural_numbers = np.linspace(1, 10, num=10)
print(natural_numbers)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [98]:
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [99]:
random_matrix_1_to_10 = np.random.randint(1, 11, size=(5, 5))
print(random_matrix_1_to_10)

[[ 2  1  9  5  1]
 [10  7  3  5  2]
 [ 6  4  5  5  4]
 [ 8  2  2  8  8]
 [ 1  3 10 10  4]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [100]:
random_matrix_0_to_1 = np.random.rand(4, 4)
print(random_matrix_0_to_1)

[[0.01525497 0.59884338 0.60380454 0.10514769]
 [0.38194344 0.03647606 0.89041156 0.98092086]
 [0.05994199 0.89054594 0.5769015  0.74247969]
 [0.63018394 0.58184219 0.02043913 0.21002658]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [101]:
vector_a = np.random.randint(1, 11, size=5)
vector_b = np.random.randint(1, 11, size=5)
print(vector_a + vector_b)
print(vector_a - vector_b)
print(vector_a * vector_b)

[11 10  6 18 11]
[-3  2 -4  2 -3]
[28 24  5 80 28]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [102]:
vector_c = np.random.rand(7)
vector_d = np.random.rand(7)
print(np.dot(vector_c, vector_d))

1.2441864613911515


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [103]:
matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
print(np.dot(matrix_2x2, matrix_2x3))

[[52 48 70]
 [44 60 80]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [104]:
matrix_inv = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(matrix_inv))

[[-0.09589041  0.25342466 -0.23972603]
 [-0.05479452 -0.21232877  0.3630137 ]
 [ 0.19178082 -0.00684932 -0.02054795]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [105]:
matrix_T = np.random.rand(4, 4)
print(matrix_T.T)

[[0.0920556  0.52803522 0.80545054 0.54040458]
 [0.46349802 0.99215804 0.75434899 0.29679375]
 [0.50869889 0.39503593 0.31306644 0.1107879 ]
 [0.08846017 0.33559644 0.63403668 0.3126403 ]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [106]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
print(np.dot(matrix_3x4, vector_4))

[107 146  83]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [107]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
print(np.dot(matrix_2x3, vector_3))

[1.20289273 0.38895906]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [108]:
matrix_1_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2_2x2 = np.random.randint(1, 11, size=(2, 2))
print(matrix_1_2x2 * matrix_2_2x2)

[[ 2 18]
 [32 12]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [109]:
matrix_3_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_4_2x2 = np.random.randint(1, 11, size=(2, 2))
print(np.dot(matrix_3_2x2, matrix_4_2x2))

[[39 72]
 [18 32]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [110]:
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
print(matrix_5x5.sum())

1339


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [111]:
matrix_1_4x4 = np.random.randint(1, 11, size=(4, 4))
matrix_2_4x4 = np.random.randint(1, 11, size=(4, 4))
print(matrix_1_4x4 - matrix_2_4x4)

[[ 0  0 -4  2]
 [-4 -3 -6 -3]
 [ 5 -2 -2 -5]
 [ 1  2  1  2]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [112]:
matrix_3x3 = np.random.rand(3, 3)
print(matrix_3x3.sum(axis=1).reshape(-1, 1))

[[1.556543  ]
 [1.33923224]
 [1.31455554]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [113]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
print(matrix_3x4 ** 2)

[[ 16   9  81  64]
 [  4  25  49   1]
 [ 64  16 100   4]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [114]:
vector_4 = np.random.randint(1, 51, size=4)
print(np.sqrt(vector_4))

[1.73205081 4.89897949 3.60555128 6.32455532]


## Завдання 2 (додаткове, за бажанням)

Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.where(arr % 2 != 0, -1, arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [116]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8])
vector = vector.reshape(2, -1)
print(vector)

[[1 2 3 4]
 [5 6 7 8]]


Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [117]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print(np.vstack((matrix_a, matrix_b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [118]:
a = np.array([1, 2, 3])
repeat_count = len(a)
output = np.repeat(a, repeat_count)
output = np.concatenate([output, np.tile(a, np.shape(a)).flatten()])
print(output)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [119]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [120]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(np.argsort(a)[-5:][::-1])


[15 10  3  7 18]


Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [121]:
b = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(b[~np.isnan(b)])

[1. 2. 3. 5. 6. 7.]


Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [122]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(np.linalg.norm(a - b))

6.708203932499369


Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [123]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
print(fifth_index := indices[4])

8


Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

\# Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [124]:
np.random.seed(100)

a = np.random.randint(0, 5, 10)

unique, counts = np.unique(a, return_counts=True)

output = np.zeros_like(a, dtype=bool)

for value, count in zip(unique, counts):
    if count > 1:
        indices = np.where(a == value)[0]
        output[indices[1:]] = True

print(output)

[False  True False  True False False  True  True  True  True]
